name: Release
on:
  push:
    tags: "*"
  workflow_dispatch:

jobs:
  Release:
    name: Release Theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v3
        with:
          body_path: "newest-unreleased-changes.md"
          draft: false
